# Generated by Django 4.2.7 on 2023-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_contact_addtofva'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'friends'), (2, 'family'), (3, 'office')], default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
