# Generated by Django 4.2.7 on 2023-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_contact_category_contact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Friends'), (2, 'Family'), (3, 'Office')]),
        ),
    ]
