# Generated by Django 4.2.7 on 2023-12-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_remove_contact_user_usercontact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='contact',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='user',
            new_name='uid',
        ),
    ]
