# Generated by Django 4.2.7 on 2023-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_rename_contact_usercontact_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cid',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
