# Generated by Django 4.2.7 on 2023-12-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_contact_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cid',
            new_name='uid',
        ),
    ]
