# Generated by Django 4.2.7 on 2023-12-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_remove_contact_uid_contact_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_contacts',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
